### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by EpicStep**
TODO:
- [x] Refactoring IPC
- [x] Refactoring client
- [x] Edit example
- [x] Parse response
- [x] Make go-lint 100%
- [ ] Write some tests
- [ ] Add CI

### CODE REVIEW

**Comment by hugolgst** [comment]
While we're doing that I'd also include a point to make go-lint 100%, it would mean comment every exported function/struct etc.

**Comment by EpicStep** [comment]
> While we're doing that I'd also include a point to make go-lint 100%, it would mean comment every exported function/struct etc.

I think this is a good idea.

**Comment by EpicStep** [comment]
@hugolgst hi, can you check this PR? 
Also I can maintain this library. I see that many forks with good additions and it will be cool to collect ideas from them and push into origin library

**Comment by hugolgst** [comment]
sure. sorry i have been quite busy with other projects

**Comment by hugolgst** [comment]
i don't have time right now to test it how could we check that together? i don't have any tests in place unfortunately

**Comment by EpicStep** [comment]
Yes, I will check my PR and other forks today. Also I think that I can write some tests in next PR

**Comment by EpicStep** [comment]
I looked at the new versions of the discord API. They have callbacks from the client and it takes a lot of time to design a new version of the library. So I'll probably continue my experiments in another repository, as it's quite a lot of work.

**Pull request closed without merging**
