### PR TITLE
Fix package imports

### PR DESCRIPTION
**Pull request by EpicStep**

### CODE REVIEW

**Comment by EpicStep** [comment]
If all good, can you add "hacktoberfest-accepted" tag?

**Comment by gabrielmajosi** [comment]
is this repo still maintained? why is it taking so long to merge this?

**Comment by EpicStep** [comment]
> is this repo still maintained? why is it taking so long to merge this?

Hi, I don't know, but we can create fork and maintain it.

**Comment by hugolgst** [comment]
Hi, I am really sorry for this delay.

**Pull request merged**
